import './globals.css'
import { Tajawal } from 'next/font/google'

const font = Tajawal({ 
  subsets: ['latin'],
  weight: ['400', '700'],
 })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="ar" dir="rtl" >
      <body className={font.className}>{children}</body>
    </html>
  )
}
